fixtures:
  repositories:
    datacat:
      repo: "https://github.com/richardc/puppet-datacat.git"
      ref: '0.6.1'
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '2.4.0'
  symlinks:
    haproxy: "#{source_dir}"
